### ISSUE TITLE
Code review - ocena.

### ISSUE THREAD

**Issue by Willaiem** [AdamMaichrzik/reactSocialApp#1]
Cześć, widziałem twój post na grupie Praca w IT dla Stażystów i Juniorów (IT Jobs for Intern/Junior) i postanowiłem posprawdzać twoje projekty.

HTML - placeholder nie służy do oznaczania tego, do czego służy dany element - to jest do tego, aby pokazać użytkownikowi przykładowe dane, które może wprowadzić np. w inputcie służącym do emaila placeholderem mogłoby być "jankowalski@gmail.com". Zamiast tego, umieściłbym te oznaczenia w elemencie `<label>`.

CSS - osobiście bym go utrzymywał w metodyce BEM niż camelCase.

Home.jsx
- formatowanie wygląda nieschludnie - proponuję skorzystać z wtyczki Prettier.

Profile.jsx
- formatowanie jak w Home.jsx
- linijka 30 - ten span bym zastąpił `<p> `dla sementyki.

CloseFriend.jsx
- w img nie pozostawiałbym pustego "src", tylko odzwierciedlałoby to, co te zdjęcie reprezentuje np. tutaj to "person image"

Rightbar.jsx
- komponenty HomeRightbar i ProfileRightbar odseparowałbym do osobnego pliku np. Rightbar.parts.jsx lub Rightbar.home.jsx i Rightbar.profile.jsx

Login.jsx i Register.jsx
- ten element należy potraktować jako formularz, zakładając, że służyłby do przekazywania danych. Dodatkowo brakuje walidacji inputów.

Share.jsx, Sidebar.jsx i Topbar.jsx
- importowane ikony bym ponazywał, aby było wiadome, od czego są. np. PermMedia as PhotoVideoIcon

Włączyłem tą aplikację i w zasadzie ona działa 99% jak strona w czystym HTML - nie licząc możliwość "załapkowania" to nie ma możliwości na jakąkolwiek interakcję ze stroną.

Podsumowując - apka niby Reactowa, a w zasadzie zachowuje się jak standardowy szablon HTML + CSS. 
Problemem jest też fakt, że to apka 1:1 z tutoriala - nic nie zostało wprowadzone od siebie, żeby w jakikolwiek sposób wyróżniała się od tamtego klona.
Żeby ta apka miała sens musisz dodać dużo od siebie - jeśli idziemy w temat social mediów to m.in. możliwość dodawania postów, dodawania komentarzy czy czatowania ze znajomymi.

Mogę także doradzić w nauce i doborze materiałów - jestem także na FB.
Pozdrawiam.

Edit: małe poprawki, bo GH niepotrzebnie coś pousuwał.

**Comment by AdamMaichrzik** [comment]
Bardzo dziękuję za wnikliwa analizę mojego projektu. Niedługo będę chciał stworzyć jeden projekt już własny który będzie moim reprezentacyjnym projektem. Ten który sprawdziłeś tak jak napisałeś jest przepisany z tutorialu - zrobiłem to dla lepszego zapamiętania informacji.
Jakie materiały mógłbyś polecić do nauki? Jeszcze raz dziękuję za pomoc :)

**Comment by Willaiem** [comment]
Generalnie zacząłbym od doszlifowania JavaScriptu - bo to w zasadzie jest najważniejsze.

Jak ogarniesz JS'a to łatwiej tobie pójdzie z ogarnianiem Reacta.

Osobiście korzystałem z tego kursu: https://www.udemy.com/course/javascript-the-complete-guide-2020-beginner-advanced/ - i mogę go polecić - nie jest perfekcyjny ale daje radę.

Po JS możesz siąść do Reacta. 
Dlatego polecę ten kurs - https://epicreact.dev/

Jest mega dobry i sporo się tam nauczysz dobrych wzorców.

I nie musisz go kupować (dla samych filmików a bez nich się lepiej nauczyłem, ale to zależy od osoby), bo wszystko jest w repo twórcy.
Klonujesz, instalujesz zależności i ciśniesz z nauką.

(pierwsze 4 - absolutnie do zrobienia, późniejsze też są warte do obczajenia)

https://github.com/kentcdodds/react-fundamentals
https://github.com/kentcdodds/react-hooks
https://github.com/kentcdodds/advanced-react-hooks
https://github.com/kentcdodds/advanced-react-patterns
https://github.com/kentcdodds/react-performance
https://github.com/kentcdodds/testing-react-apps
https://github.com/kentcdodds/react-suspense
https://github.com/kentcdodds/bookshelf/ - ćwiczenia są w branch'ach

Potem cisnąłbym z TypeScriptem aby pisać bezpieczny kod i żeby nie wywalać się na "głupich" błędach.

Do tego polecam kursy od Adama Gospodarczyka (to specjalista w te sprawy) na https://eduweb.pl/wyszukiwarka?query=typescript

Nie musisz za nie płacić - wystarczy, że włączysz sobie darmowy trial (i masz tydzień za free, bez karty, bez żadnych ukrytych warunków).
Dodatkowo też bardzo polecam książkę "TypeScript na poważnie" Michała Miszczyszyna (kolejny koks w tej dziedzinie): https://typescriptnapowaznie.pl/

Co do CSS'a - znalazłem i kupiłem ten świetny kurs - https://css-for-js.dev/ - tyle, że jest on interaktywny, to nie jest "normalny" kurs wideo.

Jak napiszesz do mnie priv (wejść na swój post na grupie, tam dałem reakcję "Trzymaj się" i wtedy mnie znajdziesz), to mogę pomóc w załatwieniu książki i kursu w korzystniejszy sposób.

Daję też ciekawe miejsce z darmowymi materiały - https://academy.localhost-group.com/meaty/

To stronka mentora, od którego się aktualnie uczę.

Może cię przetłoczyć ilość informacji, ale nie wszystko na szczęście cię nie będzie dotyczyć.

Ale na początek z tej strony bym wziął Clean Code, aby pisać lepszy kod.
Ewentualnie ten kurs od Academind (bardzo polecam) - https://pro.academind.com/p/clean-code

No i wykłady - https://academy.localhost-group.com/records
także bardzo polecam, ale to zapisz sobie na później, ma to sens dopiero po przerobieniu JS'a i trochę Reacta bądź TS'a.

Też warto jakbyś zaangażował się w jakąś społeczność, aby wspólnie budować projekty, a nuż może trafisz na kogoś, kto poleci cię do pracy.

Na przykład ja jestem w takiej społeczności (polskiej) - https://www.clanhouse.io/ i jestem aktualnie na dwóch projektach.
Warto to obczaić.

Tak jak wcześniej wspomniałem - co do książki i kursu czy bądź jeszcze innych rzeczy to możesz pisać na priv na FB.
Pozdrawiam.
